project:
  type: website

website:
  title: "主页"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  page-footer:
    center: 
      - text: " &copy; 邱飞   浙ICP备2024072710号-1"
        href: "https://beian.miit.gov.cn"
     
format:
  html:
    theme: Journal
    css: styles.css

execute:
  freeze: auto