project:
  type: website

website:
  title: "QF"
  navbar:
    right:
      - life.qmd
      - data.qmd
      - invest.qmd
      # - icon: github
      #   href: https://github.com/
  page-footer:
    # left: |
    #   Powered By
    #   [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    left: ↑ [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center: 
      - text: "邱飞 &copy; 2008-2024"
      - text: "浙ICP备 2024072710号-1"
        href: "https://beian.miit.gov.cn"
      - text: "浙公网安备 33021202002511号"
        href: "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33021202002511"
    right:
      - icon: github 
        href: https://github.com/qiufei/qiufei.github.io
      - text: ←
format:
  html:
    theme: Journal
    css: styles.css

execute:
  freeze: auto